version: '3.8'
services:
  db:
    build: ./db
    container_name: MAV_db
    environment:
      SA_USERNAME: "sa"
      SA_PASSWORD: "Ke123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1444:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - mav-network

networks:
  mav-network:
    driver: bridge

volumes:
  mssql_data: